### ISSUE TITLE
Error in GNOME 41.3

### ISSUE THREAD

**Issue by josineto** [linux-man/nautilus-mediainfo#2]
Hi! In GNOME 41.3 (perhaps even on GNOME 41.0 because I noticed it a month or two ago), the mediainfo tab doesn't show anymore in Nautilus properties dialog.

Problem happens with any user, root or not. Running `nautilus .` doesn't emit any error. Running `sudo nautilus .` emits the following (Nautilus opens normally):

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-mediainfo.py", line 13, in <module>
    from MediaInfoDLL3 import *
ModuleNotFoundError: No module named 'MediaInfoDLL3'
```

Versions installed:
- mediainfo: 21.09-01
- libmediainfo: 21.09-01
- python-mediainfodll: 1:17.10-1
- python: 3.10.2-1
- python-nautilus: 1.2.3-7
- nautilus-mediainfo: 1.0.4-2

**Comment by linux-man** [comment]
Thank you for a very concise bug report.
It probably has nothing to do with Gnome version, but I can only test it up to 40.4.
I noticed that [python-mediainfodll](https://aur.archlinux.org/packages/python-mediainfodll) (a dependency) was updated on 2021-12-09.
At debian, mediainfo package is now installed at /usr/lib/python3/dist-packages/pymediainfo/\__init\__.py instead of /usr/lib/python3/dist-packages/MediaInfoDLL3.py.
So, if arch has the same changes, the import fails.
Can you change line 13 of nautilus-mediainfo.py from
```
from MediaInfoDLL3 import *
```
to
```
try:
  from MediaInfoDLL3 import *
except ImportError:
  from pymediainfo import *
```
The file is probably at /usr/share/nautilus-python/extensions/

**Comment by linux-man** [comment]
Maybe @yochananmarqos can give a hand...

**Comment by yochananmarqos** [comment]
I can't reproduce the issue.

> I noticed that [python-mediainfodll](https://aur.archlinux.org/packages/python-mediainfodll) (a dependency) was updated on 2021-12-09.

The upstream [`MediaInfoDLL3.py`](https://github.com/MediaArea/MediaInfoLib/blob/master/Source/MediaInfoDLL/MediaInfoDLL3.py) hasn't been touched for over two years. I've only done some fiddling with the versioning of the AUR package.

> At debian, mediainfo package is now installed at /usr/lib/python3/dist-packages/pymediainfo/_init_.py instead of /usr/lib/python3/dist-packages/MediaInfoDLL3.py.

What package are we talking about here? [`libmediainfo`](https://archlinux.org/packages/community/x86_64/libmediainfo/) =/= [`python-pymediainfo`](https://archlinux.org/packages/community/any/python-pymediainfo/). Those are two different things and I do not have `python-pymediainfo` installed. Remember, I created the `python-mediainfodll` AUR package just for this project.

**Comment by josineto** [comment]
Thank you for replying! I forgot to mention I'm in Manjaro.

I changed nautilus-mediainfo.py (it's in the location you suggested), and run `sudo nautilus .`, which gives the following:

```
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-mediainfo.py", line 14, in <module>
    from MediaInfoDLL3 import *
ModuleNotFoundError: No module named 'MediaInfoDLL3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/nautilus-mediainfo.py", line 16, in <module>
    from pymediainfo import *
ModuleNotFoundError: No module named 'pymediainfo'
```

Looking at `/usr/lib/`, there's no `python3` folder, but `python3.10`, `python3.9` and so on. None of them has folder `dist-packages`. But in `python3.9/site-packages`, I found `MediaInfoDLL3.py`. So I guess (since I've never used Python) the system is looking at `python3.10` folder (which doesn't have a trace of MediaInfo), missing it from 3.9.

How it could be solved?

**Comment by josineto** [comment]
Just for note: there's another error in nautilus related to PyPDF2 not being found. But `PyPDF2` also is on `python3.9/site-packages`. So it seems related to python versions. But python is installed via two packages, `python` (currently 3.10.2-1) and `python2` (currently 2.7.18-5). So why is it creating specific folders, like 3.8, 3.9, 3.10?

**Comment by yochananmarqos** [comment]
> sudo nautilus .

Do not run [GUI applications as root](https://wiki.archlinux.org/title/Running_GUI_applications_as_root#GVFS) like that. Instead use:

```
nautilus admin:///root/
```
You can also install `nautilus-admin` for integration.

> in python3.9/site-packages, I found MediaInfoDLL3.py. 

There's your issue. You need to rebuild your Python AUR packages for every major Python release like 3.10. Information about how to do that has been posted in every Announcement post on the Manjaro forum for the last two months or so. See the most recent [Stable Announcement.](https://forum.manjaro.org/t/stable-update-2022-02-14-kernels-haskell-cutefish-0-7-deepin-firefox-maui-2-1-1-systemd/102594)

**Comment by linux-man** [comment]
@jzeneto Does yochananmarqos explanation solved your problem?

**Comment by josineto** [comment]
@linux-man please, sorry for the silence. Yes, it did! Below are the steps I followed to solve it (steps 2-3 were necessary):

1. According to [this page](https://forum.manjaro.org/t/stable-update-2022-02-14-kernels-haskell-cutefish-0-7-deepin-firefox-maui-2-1-1-systemd/102594) (cited by @yochananmarqos ), run `yay -S $(pacman -Qoq /usr/lib/python3.9) --answerclean All` (after installing `yay`, of course)
2. Uninstall `nautilus-mediainfo` and `python-mediainfodll`
3. Reinstall them

Thank you very much for your help, and sorry again for the late response.
